"""gamification

Revision ID: 678ced16f93f
Revises: 
Create Date: 2026-03-24 11:09:39.518325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678ced16f93f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('economy_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level_4_xp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('level_5_xp', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_active_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_active_date')
        batch_op.drop_column('streak')

    with op.batch_alter_table('economy_settings', schema=None) as batch_op:
        batch_op.drop_column('level_5_xp')
        batch_op.drop_column('level_4_xp')

    # ### end Alembic commands ###
